In [17]:
import pandas as pd
import numpy as np
import pdftotext
import os
import glob

In [4]:
df = pd.read_excel("all_data.xlsx")

In [10]:
df.head()

,Asia - Long,Asia - Net,Asia - Short,Beginning Balance,Capital Call Amount ($)*,Capital Call (%),Capital Reserve Balance ($),Commitment,Consumer Discretionary - Long,Consumer Discretionary - Net,...,Category Name,Sub Category,File Name,Original File Name,Investment Structure,Last Modified,Modified by,Investment Legal Name,Investment Extraction Alias,Entity Extraction Alias
0,NaN,NaN,NaN,531250.00,NaN,NaN,NaN,1250000.0,NaN,NaN,...,Capital Activity,Account Statement,Liverpool Investments L.P. - Henderson Holding...,LiverpoolQuarterlyAcctStatements1148.pdf,Drawdown Fund,2019-01-26 17:01:27,canoe software,NaN,NaN,Henderson Holding Group LLC
1,NaN,NaN,NaN,605514.45,NaN,NaN,NaN,1250000.0,NaN,NaN,...,Capital Activity,Account Statement,Liverpool Investments L.P. - Henderson Holding...,Henderson Holding Group LLC - Liverpool Invest...,Drawdown Fund,2019-01-26 17:01:27,canoe software,NaN,NaN,Henderson Holding Group LLC
2,NaN,NaN,NaN,697346.19,NaN,NaN,NaN,1250000.0,NaN,NaN,...,Capital Activity,Account Statement,Liverpool Investments L.P. - Henderson Holding...,Henderson Holding Group LLC - Liverpool Invest...,Drawdown Fund,2019-01-26 17:01:28,canoe software,NaN,NaN,Henderson Holding Group LLC
3,NaN,NaN,NaN,723538.84,NaN,NaN,NaN,1250000.0,NaN,NaN,...,Capital Activity,Account Statement,Liverpool Investments L.P. - Henderson Holding...,Henderson Holding Group LLC - Liverpool Invest...,Drawdown Fund,2019-01-26 17:01:28,canoe software,NaN,NaN,Henderson Holding Group LLC
4,NaN,NaN,NaN,760465.85,NaN,NaN,NaN,1250000.0,NaN,NaN,...,Capital Activity,Account Statement,Liverpool Investments L.P. - Henderson Holding...,Henderson Holding Group LLC - Liverpool Invest...,Drawdown Fund,2019-01-26 17:01:28,canoe software,NaN,NaN,Henderson Holding Group LLC

In [14]:
# df[['Category Name', 'Sub Category', 'File Name']]

In [55]:
new_df = df[['Category Name', 'Sub Category', 'File Name']]

In [6]:
new_df.head()

,Category Name,Sub Category,File Name
0,Capital Activity,Account Statement,Liverpool Investments L.P. - Henderson Holding...
1,Capital Activity,Account Statement,Liverpool Investments L.P. - Henderson Holding...
2,Capital Activity,Account Statement,Liverpool Investments L.P. - Henderson Holding...
3,Capital Activity,Account Statement,Liverpool Investments L.P. - Henderson Holding...
4,Capital Activity,Account Statement,Liverpool Investments L.P. - Henderson Holding...

In [56]:
new_df = new_df[:-1]

In [44]:
new_df.shape

(276, 3)

In [114]:
new_df['Sub Category'].unique()

array(['Account Statement', 'Distribution Notice', 'Call Notice',
       'Investor Letter', 'Fact Sheet'], dtype=object)

In [45]:
def category_to_numeric(x):
    if x == 'Account Statement':
        return 1
    elif x == 'Distribution Notice':
        return 2
    elif x == 'Call Notice':
        return 3
    else:
        return -1

In [57]:
new_df['category'] = new_df['Sub Category'].apply(category_to_numeric)

In [8]:
new_df['category'].unique()

array([ 1,  2,  3, -1])

In [10]:
new_df.head()

,Category Name,Sub Category,File Name,category
0,Capital Activity,Account Statement,Liverpool Investments L.P. - Henderson Holding...,1
1,Capital Activity,Account Statement,Liverpool Investments L.P. - Henderson Holding...,1
2,Capital Activity,Account Statement,Liverpool Investments L.P. - Henderson Holding...,1
3,Capital Activity,Account Statement,Liverpool Investments L.P. - Henderson Holding...,1
4,Capital Activity,Account Statement,Liverpool Investments L.P. - Henderson Holding...,1

In [58]:
new_df = new_df.sort_values(by='File Name').reset_index()

In [59]:
new_df.head()

,index,Category Name,Sub Category,File Name,category
0,195,Capital Activity,Account Statement,Arsenal Capital Group - Wenger Partners - Acc...,1
1,199,Capital Activity,Account Statement,Arsenal Capital Group - Wenger Partners - Acc...,1
2,275,Capital Activity,Account Statement,Arsenal Capital Group - Wenger Partners - Acc...,1
3,192,Capital Activity,Account Statement,Arsenal Capital Group - Wenger Partners - Acc...,1
4,196,Capital Activity,Account Statement,Arsenal Capital Group - Wenger Partners - Acc...,1

In [14]:
len(new_df['File Name'])

276

In [47]:
import os
pdfs = os.listdir("docs/raw_data/")

In [48]:
len(pdfs)

277

In [49]:
pdfs.sort()

In [19]:
# pdfs

In [60]:
new_df['file'] = pdfs[1:]

In [21]:
import PyPDF2

In [29]:
pdfFileObj = open('docs/raw_data/Crystal Palace, LLC - Fact Sheet - 2018-06-30.pdf', 'rb')

In [30]:
pdfReader = PyPDF2.PdfFileReader(pdfFileObj)

In [31]:
pdfReader.numPages

2

In [32]:
pageObj = pdfReader.getPage(0)

In [44]:
contents = pageObj.extractText().strip()
# print(contents)

NameError: name 'pageObj' is not defined

In [22]:
import pdftotext

In [156]:
with open('docs/raw_data/Crystal Palace, LLC - Fact Sheet - 2018-06-30.pdf', 'rb') as f:
    p = pdftotext.PDF(f)

In [16]:
import nltk
# print(nltk.sent_tokenize(p[0]))

In [163]:
# for file in glob.glob('docs/raw_data/*.pdf'):
#     print(file)

In [169]:
import pdftotext
import glob
import os
import nltk
for file in glob.glob('docs/raw_data/*.pdf'):
    content = []
    with open(file, 'rb') as f:
        pdf = pdftotext.PDF(f)
#         print (pdf)
        for page in pdf:
            content += nltk.sent_tokenize(page)
#             print(content)
    filename = file.split('/')[2].split('.')[0] + '.txt'
#     print('\n'.join(content))
    f = open('text_files/'+filename, 'w')
    f.write(''.join(content))
    f.close()

In [61]:
new_df['text'] = None

In [62]:
def convert_to_text(path=None):
    row = 0
    for file in glob.glob('docs/raw_data/*.pdf'):
        content = []
        with open(file, 'rb') as f:
            pdf = pdftotext.PDF(f)
    #         print (pdf)
            for page in pdf:
                page = page.replace('\n', ' ')
    #             print(page)
                content += nltk.sent_tokenize(page)
    #     print(content)
        new_df['text'][row] = content[0]
        row += 1
#     break
#     filename = file.split('/')[2].split('.')[0] + '.txt'
# #     print('\n'.join(content))
#     f = open('text_files/'+filename, 'w')
#     f.write(''.join(content))
#     f.close()

In [63]:
convert_to_text()

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  del sys.path[0]

In [42]:
content = ''
with open("docs/raw_data/Newcastle Ventures, LLC - Henderson Holding Group - Capital Call Notice - 2017-03-20.pdf", 'rb') as f:
    pdf = pdftotext.PDF(f)
#         print (pdf)
    for page in pdf:
        page = page.replace('\n', ' ')
        content += ''.join(nltk.sent_tokenize(page))

In [43]:
content

'            Newcastle Ventures TO: Henderson Holding Group FROM: Newcastle Ventures, LLC DATE: 3/10/2017 RE: Capital Call Notice for Henderson Holding Group - Due 3/20/2017 Newcastle Ventures, GP (the “Partnership”) is issuing a capital call request in accordance with section 5.1 of the Limited Partnership Agreement (the “Agreement”).The total capital called is $27,117,728 and will be used to fund investments out of the Partnership and to pay management fees and operating expenses.Please send a wire transfer or mail a check for $145,000.00 by Monday, 20 March 2017 as follows: WIRE INSTRUCTIONS:            Institution:         Marin Valley Bank                               Account Number:      72839473                               Bank Address:        383 Juniper Rd                                                    Beverly Hills, CA 90210                               Reference:           Yedlin Capital LLC CHECK INSTRUCTIONS: If you are funding via check, please mail the check payable to Newcastle Ventures, GP to the following address:                               Newcastle Ventures                               4 Strawberry Place                               Newcastle Upon Tyne, London, UK If you have any questions regarding this notice, please contact Rafael Benitez at Rafael@newcastle.com Sincerely, Rafael Benitez General Partner'

In [64]:
new_df.head()

,index,Category Name,Sub Category,File Name,category,file,text
0,195,Capital Activity,Account Statement,Arsenal Capital Group - Wenger Partners - Acc...,1,Arsenal Capital Group - Wenger Partners - Acc...,Chelsea Partners ...
1,199,Capital Activity,Account Statement,Arsenal Capital Group - Wenger Partners - Acc...,1,Arsenal Capital Group - Wenger Partners - Acc...,Liverpool Investments 6/30/2017 To...
2,275,Capital Activity,Account Statement,Arsenal Capital Group - Wenger Partners - Acc...,1,Arsenal Capital Group - Wenger Partners - Acc...,Newcastle Ventu...
3,192,Capital Activity,Account Statement,Arsenal Capital Group - Wenger Partners - Acc...,1,Arsenal Capital Group - Wenger Partners - Acc...,4/14/2016 Courtois Investment Group 5 Fulham R...
4,196,Capital Activity,Account Statement,Arsenal Capital Group - Wenger Partners - Acc...,1,Arsenal Capital Group - Wenger Partners - Acc...,Liverpool Investments R 1/15/2...

In [65]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd
from collections import Counter
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfTransformer

In [66]:
text_list = new_df['text'].tolist()
count_vect = CountVectorizer()
x_train_counts = count_vect.fit_transform(text_list)

In [67]:
tfidf_transformer = TfidfTransformer()
x_train_tfidf = tfidf_transformer.fit_transform(x_train_counts)

In [68]:
varietal_list = new_df['category'].tolist()
train_x, test_x, train_y, test_y = train_test_split(x_train_tfidf, varietal_list, test_size=0.3)

In [69]:
from sklearn.svm import SVC

In [70]:
# clf = MultinomialNB().fit(train_x, train_y)
clf = SVC(kernel='linear').fit(train_x, train_y)
# clf = SVC(kernel='linear').fit(x_train_tfidf, varietal_list)
y_score = clf.predict(test_x)

In [71]:
np.mean(y_score != test_y)

0.4819277108433735

In [66]:
y_score

array([1, 1, 1, 1, 1, 3, 1, 1, 1, 1, 3, 3, 1, 1, 3, 1, 1, 1, 3, 1, 1, 3,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 3, 1, 1, 1, 1, 3, 1, 1, 1, 3,
       1, 1, 1, 3, 1, 1, 1, 1, 1, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 3, 1, 1, 1, 1, 1, 1, 1, 1, 3, 1, 1, 3, 1, 1, 1])

In [1]:
import glob

In [2]:
for file in glob.glob("docs/new/*.pdf"):
    print(file)

docs/new/Ellis Lake - Class B - Portage Capital - Account Statement - 2014-01-31.pdf
docs/new/LionEye Fund LP - Portage Capital - Account Statement - 2013-12-31.pdf
docs/new/River Birch Partners, LP - Portage Capital - Account Statement - 2014-06-30.pdf
docs/new/River Birch Partners, LP - Four L Partners - Account Statement - 2013-12-31.pdf
docs/new/LionEye Fund LP - Four L Partners - Account Statement - 2014-06-30.pdf
docs/new/LionEye Fund LP - Portage Capital - Account Statement - 2014-04-30.pdf
docs/new/River Birch Partners, LP - Four L Partners - Account Statement - 2014-04-30.pdf
docs/new/Ellis Lake - Class B - Portage Capital - Account Statement - 2013-09-30.pdf
docs/new/LionEye Fund LP - Four L Partners - Account Statement - 2013-10-31.pdf
docs/new/Ion Israel - Portage Capital - Account Statement - 2014-02-28.pdf
docs/new/Clearline Capital - Class A Interests (Founder) - Portage Capital - Account Statement - 2014-07-31.pdf
docs/new/Clearline Capital - Class A Interests (Founder) - Portage Capital - Account Statement - 2014-02-28.pdf
docs/new/Clearline Capital - Class A Interests (Founder) - Four L Partners - Account Statement - 2014-05-31.pdf
docs/new/LNK Partners (Parallel), L.P. - Portage Capital - Account Statement - 2014-06-30.pdf
docs/new/Clearline Capital - Class A Interests (Founder) - Portage Capital - Account Statement - 2013-11-30.pdf
docs/new/Clearline Capital - Class A Interests (Founder) - Four L Partners - Account Statement - 2013-11-30.pdf
docs/new/Clearline Capital - Class A Interests (Founder) - Portage Capital - Account Statement - 2014-05-31.pdf
docs/new/Clearline Capital - Class A Interests (Founder) - Four L Partners - Account Statement - 2014-02-28.pdf
docs/new/Clearline Capital - Class A Interests (Founder) - Four L Partners - Account Statement - 2014-07-31.pdf
docs/new/LionEye Fund LP - Portage Capital - Account Statement - 2013-10-31.pdf
docs/new/River Birch Partners, LP - Portage Capital - Account Statement - 2014-04-30.pdf
docs/new/River Birch Partners, LP - Four L Partners - Account Statement - 2013-10-31.pdf
docs/new/LionEye Fund LP - Four L Partners - Account Statement - 2014-04-30.pdf
docs/new/Ellis Lake - Class B - Portage Capital - Account Statement - 2014-03-31.pdf
docs/new/LionEye Fund LP - Portage Capital - Account Statement - 2014-06-30.pdf
docs/new/River Birch Partners, LP - Four L Partners - Account Statement - 2014-06-30.pdf
docs/new/LionEye Fund LP - Four L Partners - Account Statement - 2013-12-31.pdf
docs/new/Ion Israel - Portage Capital - Account Statement - 2014-01-31.pdf
docs/new/H) - StoneRiver Capital, LP - Account Statement - 2014-06-30.pdf
docs/new/Clearline Capital - Class A Interests (Founder) - Four L Partners - Account Statement - 2014-03-31.pdf
docs/new/H) - StoneRiver Capital, LP - Account Statement - 2013-10-31.pdf
docs/new/Clearline Capital - Class A Interests (Founder) - Portage Capital - Account Statement - 2014-01-31.pdf
docs/new/Ellis Lake - Class B - Portage Capital - Account Statement - 2013-11-30.pdf
docs/new/Ellis Lake - Class B - Portage Capital - Account Statement - 2014-02-28.pdf
docs/new/MidOcean Credit Opportunity Fund LP - Class A - Portage Capital - Account Statement - 2014-04-30.pdf
docs/new/Clearline Capital - Class A Interests - Four L Partners - Account Statement - 2014-06-30.pdf
docs/new/MidOcean Credit Opportunity Fund LP - Class A - Portage Capital - Account Statement - 2013-12-31.pdf
docs/new/MidOcean Credit Opportunity Fund LP - Class A - Portage Capital - Account Statement - 2014-06-30.pdf
docs/new/Special Credit Opportunities, L.P. - Series C - Brandon Dunn - Account Statement - 2014-06-30.pdf
docs/new/MidOcean Credit Opportunity Fund LP - Class A - Portage Capital - Account Statement - 2013-10-31.pdf
docs/new/Ellis Lake - Class B - Portage Capital - Account Statement - 2014-05-31.pdf
docs/new/Clearline Capital - Class A Interests - Four L Partners - Account Statement - 2014-04-30.pdf
docs/new/H) - StoneRiver Capital, LP - Account Statement - 2014-04-30.pdf
docs/new/Clearline Capital - Class A Interests (Founder) - Four L Partners - Account Statement - 2014-01-31.pdf
docs/new/Ion Israel - Portage Capital - Account Statement - 2014-03-31.pdf
docs/new/Sandalwood - Portage Capital - Account Statement - 2014-06-30.pdf
docs/new/H) - StoneRiver Capital, LP - Account Statement - 2013-12-31.pdf
docs/new/Clearline Capital - Class A Interests (Founder) - Portage Capital - Account Statement - 2014-03-31.pdf
docs/new/H) - StoneRiver Capital, LP - Account Statement - 2013-09-30.pdf
docs/new/Clearline Capital - Class A Interests (Founder) - Four L Partners - Account Statement - 2013-12-31.pdf
docs/new/Clearline Capital - Class A Interests (Founder) - Portage Capital - Account Statement - 2014-06-30.pdf
docs/new/Clearline Capital - Class A Interests (Founder) - Four L Partners - Account Statement - 2014-04-30.pdf
docs/new/H) - StoneRiver Capital, LP - Account Statement - 2014-01-31.pdf
docs/new/Clearline Capital - Class A Interests (Founder) - Portage Capital - Account Statement - 2013-10-31.pdf
docs/new/Ion Israel - Portage Capital - Account Statement - 2014-06-30.pdf
docs/new/Redwood Domestic Fund LP - Series 1 - Portage Capital - Account Statement - 2014-01-31.pdf
docs/new/River Birch Partners, LP - Portage Capital - Account Statement - 2014-07-31.pdf
docs/new/MidOcean Credit Opportunity Fund LP - Class A - Portage Capital - Account Statement - 2014-03-31.pdf
docs/new/LionEye Fund LP - Portage Capital - Account Statement - 2014-05-31.pdf
docs/new/River Birch Partners, LP - Portage Capital - Account Statement - 2013-11-30.pdf
docs/new/LionEye Fund LP - Four L Partners - Account Statement - 2014-02-28.pdf
docs/new/River Birch Partners, LP - Four L Partners - Account Statement - 2014-05-31.pdf
docs/new/LionEye Fund LP - Four L Partners - Account Statement - 2013-11-30.pdf
docs/new/River Birch Partners, LP - Portage Capital - Account Statement - 2014-02-28.pdf
docs/new/LionEye Fund LP - Portage Capital - Account Statement - 2013-11-30.pdf
docs/new/River Birch Partners, LP - Portage Capital - Account Statement - 2014-05-31.pdf
docs/new/LionEye Fund LP - Portage Capital - Account Statement - 2014-02-28.pdf
docs/new/LionEye Fund LP - Four L Partners - Account Statement - 2014-05-31.pdf
docs/new/Clearline Capital - Class A Interests - Four L Partners - Account Statement - 2014-03-31.pdf
docs/new/MidOcean Credit Opportunity Fund LP - Class A - Portage Capital - Account Statement - 2013-09-30.pdf
docs/new/River Birch Partners, LP - Four L Partners - Account Statement - 2014-07-31.pdf
docs/new/MidOcean Credit Opportunity Fund LP - Class A - Portage Capital - Account Statement - 2014-01-31.pdf
docs/new/Clearline Capital - Class A Interests (Founder) - Four L Partners - Account Statement - 2013-10-31.pdf
docs/new/Clearline Capital - Class A Interests (Founder) - Portage Capital - Account Statement - 2014-04-30.pdf
docs/new/Clearline Capital - Class A Interests (Founder) - Four L Partners - Account Statement - 2014-06-30.pdf
docs/new/H) - StoneRiver Capital, LP - Account Statement - 2014-03-31.pdf
docs/new/Clearline Capital - Class A Interests (Founder) - Portage Capital - Account Statement - 2013-12-31.pdf
docs/new/MidOcean Credit Opportunity Fund LP - Class A - Portage Capital - Account Statement - 2014-05-31.pdf
docs/new/River Birch Partners, LP - Four L Partners - Account Statement - 2014-03-31.pdf
docs/new/LionEye Fund LP - Portage Capital - Account Statement - 2014-03-31.pdf
docs/new/Ellis Lake - Class B - Portage Capital - Account Statement - 2013-10-31.pdf
docs/new/LionEye Fund LP - Four L Partners - Account Statement - 2013-09-30.pdf
docs/new/Clearline Capital - Class A Interests - Four L Partners - Account Statement - 2014-02-28.pdf
docs/new/LionEye Fund LP - Four L Partners - Account Statement - 2014-01-31.pdf
docs/new/River Birch Partners, LP - Portage Capital - Account Statement - 2014-01-31.pdf
docs/new/Clearline Capital - Class A Interests - Four L Partners - Account Statement - 2014-07-31.pdf
docs/new/Ellis Lake - Class B - Portage Capital - Account Statement - 2014-06-30.pdf
docs/new/H) - StoneRiver Capital, LP - Account Statement - 2013-11-30.pdf
docs/new/H) - StoneRiver Capital, LP - Account Statement - 2014-02-28.pdf
docs/new/LNK Partners (Parallel), L.P. - Portage Capital - Account Statement - 2013-09-30.pdf
docs/new/H) - StoneRiver Capital, LP - Account Statement - 2014-05-31.pdf
docs/new/Ellis Lake - Class B - Portage Capital - Account Statement - 2013-12-31.pdf
docs/new/LionEye Fund LP - Portage Capital - Account Statement - 2014-01-31.pdf
docs/new/Clearline Capital - Class A Interests - Four L Partners - Account Statement - 2014-05-31.pdf
docs/new/Ellis Lake - Class B - Portage Capital - Account Statement - 2014-04-30.pdf
docs/new/LionEye Fund LP - Portage Capital - Account Statement - 2013-09-30.pdf
docs/new/LionEye Fund LP - Four L Partners - Account Statement - 2014-03-31.pdf
docs/new/River Birch Partners, LP - Portage Capital - Account Statement - 2014-03-31.pdf
docs/new/MidOcean Credit Opportunity Fund LP - Class A - Portage Capital - Account Statement - 2014-02-28.pdf
docs/new/MidOcean Credit Opportunity Fund LP - Class A - Portage Capital - Account Statement - 2013-11-30.pdf

In [14]:
import os
new_pdfs = pdfs = os.listdir("docs/new/")
len(new_pdfs)

100

In [72]:
new_pdfs.sort()

In [73]:
new_pdfs

['Clearline Capital - Class A Interests (Founder) - Four L Partners - Account Statement - 2013-10-31.pdf',
 'Clearline Capital - Class A Interests (Founder) - Four L Partners - Account Statement - 2013-11-30.pdf',
 'Clearline Capital - Class A Interests (Founder) - Four L Partners - Account Statement - 2013-12-31.pdf',
 'Clearline Capital - Class A Interests (Founder) - Four L Partners - Account Statement - 2014-01-31.pdf',
 'Clearline Capital - Class A Interests (Founder) - Four L Partners - Account Statement - 2014-02-28.pdf',
 'Clearline Capital - Class A Interests (Founder) - Four L Partners - Account Statement - 2014-03-31.pdf',
 'Clearline Capital - Class A Interests (Founder) - Four L Partners - Account Statement - 2014-04-30.pdf',
 'Clearline Capital - Class A Interests (Founder) - Four L Partners - Account Statement - 2014-05-31.pdf',
 'Clearline Capital - Class A Interests (Founder) - Four L Partners - Account Statement - 2014-06-30.pdf',
 'Clearline Capital - Class A Interests (Founder) - Four L Partners - Account Statement - 2014-07-31.pdf',
 'Clearline Capital - Class A Interests (Founder) - Portage Capital - Account Statement - 2013-10-31.pdf',
 'Clearline Capital - Class A Interests (Founder) - Portage Capital - Account Statement - 2013-11-30.pdf',
 'Clearline Capital - Class A Interests (Founder) - Portage Capital - Account Statement - 2013-12-31.pdf',
 'Clearline Capital - Class A Interests (Founder) - Portage Capital - Account Statement - 2014-01-31.pdf',
 'Clearline Capital - Class A Interests (Founder) - Portage Capital - Account Statement - 2014-02-28.pdf',
 'Clearline Capital - Class A Interests (Founder) - Portage Capital - Account Statement - 2014-03-31.pdf',
 'Clearline Capital - Class A Interests (Founder) - Portage Capital - Account Statement - 2014-04-30.pdf',
 'Clearline Capital - Class A Interests (Founder) - Portage Capital - Account Statement - 2014-05-31.pdf',
 'Clearline Capital - Class A Interests (Founder) - Portage Capital - Account Statement - 2014-06-30.pdf',
 'Clearline Capital - Class A Interests (Founder) - Portage Capital - Account Statement - 2014-07-31.pdf',
 'Clearline Capital - Class A Interests - Four L Partners - Account Statement - 2014-02-28.pdf',
 'Clearline Capital - Class A Interests - Four L Partners - Account Statement - 2014-03-31.pdf',
 'Clearline Capital - Class A Interests - Four L Partners - Account Statement - 2014-04-30.pdf',
 'Clearline Capital - Class A Interests - Four L Partners - Account Statement - 2014-05-31.pdf',
 'Clearline Capital - Class A Interests - Four L Partners - Account Statement - 2014-06-30.pdf',
 'Clearline Capital - Class A Interests - Four L Partners - Account Statement - 2014-07-31.pdf',
 'Ellis Lake - Class B - Portage Capital - Account Statement - 2013-09-30.pdf',
 'Ellis Lake - Class B - Portage Capital - Account Statement - 2013-10-31.pdf',
 'Ellis Lake - Class B - Portage Capital - Account Statement - 2013-11-30.pdf',
 'Ellis Lake - Class B - Portage Capital - Account Statement - 2013-12-31.pdf',
 'Ellis Lake - Class B - Portage Capital - Account Statement - 2014-01-31.pdf',
 'Ellis Lake - Class B - Portage Capital - Account Statement - 2014-02-28.pdf',
 'Ellis Lake - Class B - Portage Capital - Account Statement - 2014-03-31.pdf',
 'Ellis Lake - Class B - Portage Capital - Account Statement - 2014-04-30.pdf',
 'Ellis Lake - Class B - Portage Capital - Account Statement - 2014-05-31.pdf',
 'Ellis Lake - Class B - Portage Capital - Account Statement - 2014-06-30.pdf',
 'H) - StoneRiver Capital, LP - Account Statement - 2013-09-30.pdf',
 'H) - StoneRiver Capital, LP - Account Statement - 2013-10-31.pdf',
 'H) - StoneRiver Capital, LP - Account Statement - 2013-11-30.pdf',
 'H) - StoneRiver Capital, LP - Account Statement - 2013-12-31.pdf',
 'H) - StoneRiver Capital, LP - Account Statement - 2014-01-31.pdf',
 'H) - StoneRiver Capital, LP - Account Statement - 2014-02-28.pdf',
 'H) - StoneRiver Capital, LP - Account Statement - 2014-03-31.pdf',
 'H) - StoneRiver Capital, LP - Account Statement - 2014-04-30.pdf',
 'H) - StoneRiver Capital, LP - Account Statement - 2014-05-31.pdf',
 'H) - StoneRiver Capital, LP - Account Statement - 2014-06-30.pdf',
 'Ion Israel - Portage Capital - Account Statement - 2014-01-31.pdf',
 'Ion Israel - Portage Capital - Account Statement - 2014-02-28.pdf',
 'Ion Israel - Portage Capital - Account Statement - 2014-03-31.pdf',
 'Ion Israel - Portage Capital - Account Statement - 2014-06-30.pdf',
 'LNK Partners (Parallel), L.P. - Portage Capital - Account Statement - 2013-09-30.pdf',
 'LNK Partners (Parallel), L.P. - Portage Capital - Account Statement - 2014-06-30.pdf',
 'LionEye Fund LP - Four L Partners - Account Statement - 2013-09-30.pdf',
 'LionEye Fund LP - Four L Partners - Account Statement - 2013-10-31.pdf',
 'LionEye Fund LP - Four L Partners - Account Statement - 2013-11-30.pdf',
 'LionEye Fund LP - Four L Partners - Account Statement - 2013-12-31.pdf',
 'LionEye Fund LP - Four L Partners - Account Statement - 2014-01-31.pdf',
 'LionEye Fund LP - Four L Partners - Account Statement - 2014-02-28.pdf',
 'LionEye Fund LP - Four L Partners - Account Statement - 2014-03-31.pdf',
 'LionEye Fund LP - Four L Partners - Account Statement - 2014-04-30.pdf',
 'LionEye Fund LP - Four L Partners - Account Statement - 2014-05-31.pdf',
 'LionEye Fund LP - Four L Partners - Account Statement - 2014-06-30.pdf',
 'LionEye Fund LP - Portage Capital - Account Statement - 2013-09-30.pdf',
 'LionEye Fund LP - Portage Capital - Account Statement - 2013-10-31.pdf',
 'LionEye Fund LP - Portage Capital - Account Statement - 2013-11-30.pdf',
 'LionEye Fund LP - Portage Capital - Account Statement - 2013-12-31.pdf',
 'LionEye Fund LP - Portage Capital - Account Statement - 2014-01-31.pdf',
 'LionEye Fund LP - Portage Capital - Account Statement - 2014-02-28.pdf',
 'LionEye Fund LP - Portage Capital - Account Statement - 2014-03-31.pdf',
 'LionEye Fund LP - Portage Capital - Account Statement - 2014-04-30.pdf',
 'LionEye Fund LP - Portage Capital - Account Statement - 2014-05-31.pdf',
 'LionEye Fund LP - Portage Capital - Account Statement - 2014-06-30.pdf',
 'MidOcean Credit Opportunity Fund LP - Class A - Portage Capital - Account Statement - 2013-09-30.pdf',
 'MidOcean Credit Opportunity Fund LP - Class A - Portage Capital - Account Statement - 2013-10-31.pdf',
 'MidOcean Credit Opportunity Fund LP - Class A - Portage Capital - Account Statement - 2013-11-30.pdf',
 'MidOcean Credit Opportunity Fund LP - Class A - Portage Capital - Account Statement - 2013-12-31.pdf',
 'MidOcean Credit Opportunity Fund LP - Class A - Portage Capital - Account Statement - 2014-01-31.pdf',
 'MidOcean Credit Opportunity Fund LP - Class A - Portage Capital - Account Statement - 2014-02-28.pdf',
 'MidOcean Credit Opportunity Fund LP - Class A - Portage Capital - Account Statement - 2014-03-31.pdf',
 'MidOcean Credit Opportunity Fund LP - Class A - Portage Capital - Account Statement - 2014-04-30.pdf',
 'MidOcean Credit Opportunity Fund LP - Class A - Portage Capital - Account Statement - 2014-05-31.pdf',
 'MidOcean Credit Opportunity Fund LP - Class A - Portage Capital - Account Statement - 2014-06-30.pdf',
 'Redwood Domestic Fund LP - Series 1 - Portage Capital - Account Statement - 2014-01-31.pdf',
 'River Birch Partners, LP - Four L Partners - Account Statement - 2013-10-31.pdf',
 'River Birch Partners, LP - Four L Partners - Account Statement - 2013-12-31.pdf',
 'River Birch Partners, LP - Four L Partners - Account Statement - 2014-03-31.pdf',
 'River Birch Partners, LP - Four L Partners - Account Statement - 2014-04-30.pdf',
 'River Birch Partners, LP - Four L Partners - Account Statement - 2014-05-31.pdf',
 'River Birch Partners, LP - Four L Partners - Account Statement - 2014-06-30.pdf',
 'River Birch Partners, LP - Four L Partners - Account Statement - 2014-07-31.pdf',
 'River Birch Partners, LP - Portage Capital - Account Statement - 2013-11-30.pdf',
 'River Birch Partners, LP - Portage Capital - Account Statement - 2014-01-31.pdf',
 'River Birch Partners, LP - Portage Capital - Account Statement - 2014-02-28.pdf',
 'River Birch Partners, LP - Portage Capital - Account Statement - 2014-03-31.pdf',
 'River Birch Partners, LP - Portage Capital - Account Statement - 2014-04-30.pdf',
 'River Birch Partners, LP - Portage Capital - Account Statement - 2014-05-31.pdf',
 'River Birch Partners, LP - Portage Capital - Account Statement - 2014-06-30.pdf',
 'River Birch Partners, LP - Portage Capital - Account Statement - 2014-07-31.pdf',
 'Sandalwood - Portage Capital - Account Statement - 2014-06-30.pdf',
 'Special Credit Opportunities, L.P. - Series C - Brandon Dunn - Account Statement - 2014-06-30.pdf']

In [74]:
'Clearline Capital - Class A Interests (Founder) - Four L Partners - Account Statement - 2013-10-31.pdf'.split(' - ')

['Clearline Capital',
 'Class A Interests (Founder)',
 'Four L Partners',
 'Account Statement',
 '2013-10-31.pdf']

In [75]:
new_df.head()

,index,Category Name,Sub Category,File Name,category,file,text
0,195,Capital Activity,Account Statement,Arsenal Capital Group - Wenger Partners - Acc...,1,Arsenal Capital Group - Wenger Partners - Acc...,Chelsea Partners ...
1,199,Capital Activity,Account Statement,Arsenal Capital Group - Wenger Partners - Acc...,1,Arsenal Capital Group - Wenger Partners - Acc...,Liverpool Investments 6/30/2017 To...
2,275,Capital Activity,Account Statement,Arsenal Capital Group - Wenger Partners - Acc...,1,Arsenal Capital Group - Wenger Partners - Acc...,Newcastle Ventu...
3,192,Capital Activity,Account Statement,Arsenal Capital Group - Wenger Partners - Acc...,1,Arsenal Capital Group - Wenger Partners - Acc...,4/14/2016 Courtois Investment Group 5 Fulham R...
4,196,Capital Activity,Account Statement,Arsenal Capital Group - Wenger Partners - Acc...,1,Arsenal Capital Group - Wenger Partners - Acc...,Liverpool Investments R 1/15/2...

In [77]:
new_df.columns

Index(['index', 'Category Name', 'Sub Category', 'File Name', 'category',
       'file', 'text'],
      dtype='object')

In [79]:
df2 = pd.DataFrame(columns=['index', 'Category Name', 'Sub Category', 'File Name', 'category',
       'file', 'text'])

In [82]:
for file in new_pdfs:
    sub_category = file.split(' - ')[-2]
    content = []
    with open("docs/new/"+file, 'rb') as f:
        pdf = pdftotext.PDF(f)
#         print (pdf)
        for page in pdf:
            page = page.replace('\n', ' ')
#             print(page)
            content += nltk.sent_tokenize(page)
#     print(content)
#     new_df['text'][row] = content[0]
    cat = category_to_numeric(sub_category)
    df2 = df2.append({'Sub Category': sub_category, 'file': file, 'text': content[0], 'category': cat}, ignore_index=True)

In [85]:
df2['text'][0]

'                                                                   Capital Account Statement  FOUR L PARTNERS LLC                                                                                                                    Run Date:                      11/08/2013                                                                                                                                 Period Start Date:                     09/30/2013                                                                                                                                  Period End Date:                      10/31/2013                                                                                                                           Share Partner Class ID:                        13-124951                                                                                                                                       Investor ID:                       40-068587                                                                                                                                       Account ID:                        41-150705                                                                                                                            Investment Profile ID:               42-124951-150705                                                                                                                                         Currency:                              USD  Account Description: FOUR L PARTNERS LLC                                                           CLEARLINE CAPITAL PARTNERS LP                                                              CLASS A INTERESTS (FOUNDER)                                                                                                                         October                                      Year to Date  Beginning Equity                                                                                                       518,922                                                   -  Capital Additions                                                                                                             -                                           500,000  Capital Withdrawals                                                                                                           -                                                  -  Net Gain/(Loss)                                                                                                          13,400                                            32,322  Ending Equity                                                                                                          532,322                                            532,322  Net Rate of Return for the Period                                                                                         2.58%                                             6.46% Net results reflect the deduction of all operational expenses (including brokerage commissions), management fees and potential profit allocation to the General Partner.'

In [86]:
df2.head(10)

,index,Category Name,Sub Category,File Name,category,file,text
0,NaN,NaN,Account Statement,NaN,1,Clearline Capital - Class A Interests (Founder...,...
1,NaN,NaN,Account Statement,NaN,1,Clearline Capital - Class A Interests (Founder...,...
2,NaN,NaN,Account Statement,NaN,1,Clearline Capital - Class A Interests (Founder...,...
3,NaN,NaN,Account Statement,NaN,1,Clearline Capital - Class A Interests (Founder...,...
4,NaN,NaN,Account Statement,NaN,1,Clearline Capital - Class A Interests (Founder...,...
5,NaN,NaN,Account Statement,NaN,1,Clearline Capital - Class A Interests (Founder...,...
6,NaN,NaN,Account Statement,NaN,1,Clearline Capital - Class A Interests (Founder...,...
7,NaN,NaN,Account Statement,NaN,1,Clearline Capital - Class A Interests (Founder...,...
8,NaN,NaN,Account Statement,NaN,1,Clearline Capital - Class A Interests (Founder...,...
9,NaN,NaN,Account Statement,NaN,1,Clearline Capital - Class A Interests (Founder...,...

In [87]:
new_df.append(df2)

,index,Category Name,Sub Category,File Name,category,file,text
0,195,Capital Activity,Account Statement,Arsenal Capital Group - Wenger Partners - Acc...,1,Arsenal Capital Group - Wenger Partners - Acc...,Chelsea Partners ...
1,199,Capital Activity,Account Statement,Arsenal Capital Group - Wenger Partners - Acc...,1,Arsenal Capital Group - Wenger Partners - Acc...,Liverpool Investments 6/30/2017 To...
2,275,Capital Activity,Account Statement,Arsenal Capital Group - Wenger Partners - Acc...,1,Arsenal Capital Group - Wenger Partners - Acc...,Newcastle Ventu...
3,192,Capital Activity,Account Statement,Arsenal Capital Group - Wenger Partners - Acc...,1,Arsenal Capital Group - Wenger Partners - Acc...,4/14/2016 Courtois Investment Group 5 Fulham R...
4,196,Capital Activity,Account Statement,Arsenal Capital Group - Wenger Partners - Acc...,1,Arsenal Capital Group - Wenger Partners - Acc...,Liverpool Investments R 1/15/2...
5,200,Capital Activity,Account Statement,Arsenal Capital Group - Wenger Partners - Acc...,1,Arsenal Capital Group - Wenger Partners - Acc...,Tottenham Hotspur...
6,193,Capital Activity,Account Statement,Arsenal Capital Group - Wenger Partners - Acc...,1,Arsenal Capital Group - Wenger Partners - Acc...,...
7,197,Capital Activity,Account Statement,Arsenal Capital Group - Wenger Partners - Acc...,1,Arsenal Capital Group - Wenger Partners - Acc...,Arsenal Capital Group R 9/12/2...
8,201,Capital Activity,Account Statement,Arsenal Capital Group - Wenger Partners - Acc...,1,Arsenal Capital Group - Wenger Partners - Acc...,Capital Account Stateme...
9,194,Capital Activity,Account Statement,Arsenal Capital Group - Wenger Partners - Acc...,1,Arsenal Capital Group - Wenger Partners - Acc...,Chelsea Partners ...
10,198,Capital Activity,Account Statement,Arsenal Capital Group - Wenger Partners - Acc...,1,Arsenal Capital Group - Wenger Partners - Acc...,...
11,202,Capital Activity,Account Statement,Arsenal Capital Group - Wenger Partners - Acc...,1,Arsenal Capital Group - Wenger Partners - Acc...,Chelsea Partn...
12,24,Capital Activity,Call Notice,Arsenal Capital Group - Wenger Partners - Cal...,3,Arsenal Capital Group - Wenger Partners - Cap...,Liverpool Investments 2/28/2015 ...
13,112,Capital Activity,Call Notice,Arsenal Capital Group - Wenger Partners - Cal...,3,Arsenal Capital Group - Wenger Partners - Cap...,Ma n ...
14,116,Capital Activity,Call Notice,Arsenal Capital Group - Wenger Partners - Cal...,3,Arsenal Capital Group - Wenger Partners - Cap...,Newcastle Ventures TO: Henderson H...
15,23,Capital Activity,Call Notice,Arsenal Capital Group - Wenger Partners - Cal...,3,Arsenal Capital Group - Wenger Partners - Cap...,Chelsea Partners ...
16,109,Capital Activity,Call Notice,Arsenal Capital Group - Wenger Partners - Cal...,3,Arsenal Capital Group - Wenger Partners - Cap...,Chelsea Partners ...
17,113,Capital Activity,Call Notice,Arsenal Capital Group - Wenger Partners - Cal...,3,Arsenal Capital Group - Wenger Partners - Cap...,Liverpool Investments 12/31/2016 T...
18,118,Capital Activity,Call Notice,Arsenal Capital Group - Wenger Partners - Cal...,3,Arsenal Capital Group - Wenger Partners - Cap...,Liverpool Investments 8/31/2014 ...
19,107,Capital Activity,Call Notice,Arsenal Capital Group - Wenger Partners - Cal...,3,Arsenal Capital Group - Wenger Partners - Cap...,10/14/2017 Courtois Investment Group 5 Fulham ...
20,110,Capital Activity,Call Notice,Arsenal Capital Group - Wenger Partners - Cal...,3,Arsenal Capital Group - Wenger Partners - Cap...,Newcastle Ventu...
21,114,Capital Activity,Call Notice,Arsenal Capital Group - Wenger Partners - Cal...,3,Arsenal Capital Group - Wenger Partners - Cap...,Tottenham Hotspur...
22,117,Capital Activity,Call Notice,Arsenal Capital Group - Wenger Partners - Cal...,3,Arsenal Capital Group - Wenger Partners - Cap...,Arsenal Capital Group To: Wenger Par...
23,108,Capital Activity,Call Notice,Arsenal Capital Group - Wenger Partners - Cal...,3,Arsenal Capital Group - Wenger Partners - Cap...,Capital Account Stateme...
24,111,Capital Activity,Call Notice,Arsenal Capital Group - Wenger Partners - Cal...,3,Arsenal Capital Group - Wenger Partners - Cap...,Chelsea Partners ...
25,115,Capital Activity,Call Notice,Arsenal Capital Group - Wenger Partners - Cal...,3,Arsenal Capital Group - Wenger Partners - Cap...,Chelsea Partn...
26,143,Capital Activity,Distribution Notice,Arsenal Capital Group - Wenger Partners - Dis...,2,Arsenal Capital Group - Wenger Partners - Cap...,Chelsea Partners ...
27,141,Capital Activity,Distribution Notice,Arsenal Capital Group - Wenger Partners - Dis...,2,Arsenal Capital Group - Wenger Partners - Cap...,Newcastle Ventures TO: Henderson H...
28,144,Capital Activity,Distribution Notice,Arsenal Capital Group - Wenger Partners - Dis...,2,Arsenal Capital Group - Wenger Partners - Cap...,...
29,142,Capital Activity,Distribution Notice,Arsenal Capital Group - Wenger Partners - Dis...,2,Arsenal Capital Group - Wenger Partners - Cap...,Chelsea Partners ...
...,...,...,...,...,...,...,...
70,NaN,NaN,Account Statement,NaN,1,LionEye Fund LP - Portage Capital - Account St...,LionEye Fund LP ...
71,NaN,NaN,Account Statement,NaN,1,LionEye Fund LP - Portage Capital - Account St...,LionEye Fund LP ...
72,NaN,NaN,Account Statement,NaN,1,MidOcean Credit Opportunity Fund LP - Class A ...,MIDOCEAN CREDIT...
73,NaN,NaN,Account Statement,NaN,1,MidOcean Credit Opportunity Fund LP - Class A ...,MIDOCEAN CREDIT...
74,NaN,NaN,Account Statement,NaN,1,MidOcean Credit Opportunity Fund LP - Class A ...,MIDOCEAN CREDIT...
75,NaN,NaN,Account Statement,NaN,1,MidOcean Credit Opportunity Fund LP - Class A ...,MIDOCEAN CREDIT...
76,NaN,NaN,Account Statement,NaN,1,MidOcean Credit Opportunity Fund LP - Class A ...,MIDOCEAN CREDIT...
77,NaN,NaN,Account Statement,NaN,1,MidOcean Credit Opportunity Fund LP - Class A ...,MIDOCEAN CREDIT...
78,NaN,NaN,Account Statement,NaN,1,MidOcean Credit Opportunity Fund LP - Class A ...,MIDOCEAN CREDIT...
79,NaN,NaN,Account Statement,NaN,1,MidOcean Credit Opportunity Fund LP - Class A ...,MIDOCEAN CREDIT...
80,NaN,NaN,Account Statement,NaN,1,MidOcean Credit Opportunity Fund LP - Class A ...,MIDOCEAN CREDIT...
81,NaN,NaN,Account Statement,NaN,1,MidOcean Credit Opportunity Fund LP - Class A ...,MIDOCEAN CREDIT...
82,NaN,NaN,Account Statement,NaN,1,Redwood Domestic Fund LP - Series 1 - Portage ...,...
83,NaN,NaN,Account Statement,NaN,1,"River Birch Partners, LP - Four L Partners - A...","River Birch Partners, LP Four L Partn..."
84,NaN,NaN,Account Statement,NaN,1,"River Birch Partners, LP - Four L Partners - A...","River Birch Partners, LP Four L Partn..."
85,NaN,NaN,Account Statement,NaN,1,"River Birch Partners, LP - Four L Partners - A...","River Birch Partners, LP Four L Part..."
86,NaN,NaN,Account Statement,NaN,1,"River Birch Partners, LP - Four L Partners - A...","River Birch Partners, LP Four L Part..."
87,NaN,NaN,Account Statement,NaN,1,"River Birch Partners, LP - Four L Partners - A...","River Birch Partners, LP Four L Part..."
88,NaN,NaN,Account Statement,NaN,1,"River Birch Partners, LP - Four L Partners - A...","River Birch Partners, LP Four L Part..."
89,NaN,NaN,Account Statement,NaN,1,"River Birch Partners, LP - Four L Partners - A...","River Birch Partners, LP Four L Part..."
90,NaN,NaN,Account Statement,NaN,1,"River Birch Partners, LP - Portage Capital - A...","River Birch Partners, LP Portage Capi..."
91,NaN,NaN,Account Statement,NaN,1,"River Birch Partners, LP - Portage Capital - A...","River Birch Partners, LP Portage Cap..."
92,NaN,NaN,Account Statement,NaN,1,"River Birch Partners, LP - Portage Capital - A...","River Birch Partners, LP Portage Cap..."
93,NaN,NaN,Account Statement,NaN,1,"River Birch Partners, LP - Portage Capital - A...","River Birch Partners, LP Portage Cap..."
94,NaN,NaN,Account Statement,NaN,1,"River Birch Partners, LP - Portage Capital - A...","River Birch Partners, LP Portage Cap..."
95,NaN,NaN,Account Statement,NaN,1,"River Birch Partners, LP - Portage Capital - A...","River Birch Partners, LP Portage Cap..."
96,NaN,NaN,Account Statement,NaN,1,"River Birch Partners, LP - Portage Capital - A...","River Birch Partners, LP Portage Cap..."
97,NaN,NaN,Account Statement,NaN,1,"River Birch Partners, LP - Portage Capital - A...","River Birch Partners, LP Portage Cap..."
98,NaN,NaN,Account Statement,NaN,1,Sandalwood - Portage Capital - Account Stateme...,100-5900 Hurontario Street Tel.
99,NaN,NaN,Account Statement,NaN,1,"Special Credit Opportunities, L.P. - Series C ...","Special Credit Opportunities, L.P. - Series C..."

In [91]:
text_list = new_df['text'].tolist()
count_vect = CountVectorizer()
x_train_counts = count_vect.fit_transform(text_list)

In [92]:
tfidf_transformer = TfidfTransformer()
x_train_tfidf = tfidf_transformer.fit_transform(x_train_counts)

In [93]:
train_x, test_x, train_y, test_y = train_test_split(x_train_tfidf, varietal_list, test_size=0.3)

In [94]:
clf = SVC(kernel='linear').fit(train_x, train_y)
y_score = clf.predict(test_x)

In [95]:
np.mean(y_score != test_y)

0.5180722891566265